module.exports = {
  language: "ja",
  theme: "theme_print.css",
  entry: [
    "example/inside-cover_01.md",
    {
      path: "example/toc_02.md",
      rel: 'contents',
    },
    "example/illust-dolphilia.md",
    "example/illust-yusan.md",
    "example/illust-mirakure.md",
    "example/illust-kepi.md",
    "example/illust-uroko.md",
    "example/illust-hozuki.md",
    "example/illust-masato.md",
    "example/illust-tattsu.md",
    "example/illust-ketosu.md",
    "example/illust-kotsubaki.md",
    "example/illust-ruri.md",
    "example/illust-senzo.md",
    "example/illust-amane.md",
    "example/illust-tachiban_a.md",
    "example/illust-tachiban_b.md",
    "example/illust-tabibito.md",
    "example/text_01.md",
    "example/list-of-works_01.md",
    "example/colophon_01.md",
  ],
  output: [
    {
      path: "./book.pdf",
      format: "pdf",
    },
  ],
};
